[package]
name = "rand-pwd-user-defined-set-6"
version = "0.1.0"
authors = ["frankhart <siddharthadhar.soumen@srmuniv.edu.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"