[package]
name = "test-parallel-elements-of-collection-match-predicate-8"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"